name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bitsdojo_window: ^0.1.6
  codiaq_editor:
    path: ../
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  markdown_widget: ^2.3.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
