name: codiaq_editor
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^7.4.5
  markdown_widget: ^2.3.2+8
  ffi: ^2.1.4
  xterm: ^4.0.0
  flutter_pty: ^0.4.2
  watcher: ^1.1.2
  path_provider: ^2.1.5
  bitsdojo_window: ^0.1.6
  material_design_icons_flutter: ^7.0.7296
  reorderable_tabbar:
    path: ../reorderable_tabbar
  codiaq_lsp:
    path: ../codiaq_lsp

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Seti
      fonts:
        - asset: assets/fonts/seti.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/JetBrainsMono-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JetBrainsMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/JetBrainsMono-ThinItalic.ttf
          weight: 100
          style: italic

    - family: JetBrainsMonoNL
      fonts:
        - asset: assets/fonts/JetBrainsMonoNL-Regular.ttf
        - asset: assets/fonts/JetBrainsMonoNL-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMonoNL-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/JetBrainsMonoNL-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMonoNL-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMonoNL-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/JetBrainsMonoNL-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMonoNL-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/JetBrainsMonoNL-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/JetBrainsMonoNL-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/JetBrainsMonoNL-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMonoNL-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/JetBrainsMonoNL-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JetBrainsMonoNL-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/JetBrainsMonoNL-Thin.ttf
          weight: 100
        - asset: assets/fonts/JetBrainsMonoNL-ThinItalic.ttf
          weight: 100
          style: italic
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
